input:
  label: "ping_generator"
  generate:
    mapping: |
      root.ts = now()
      root.unix = timestamp_unix()
    interval: 1s
    count: 0
    batch_size: 10
    auto_replay_nacks: true

pipeline:
  processors:
    - mapping: |
        root = this

output:
  label: broker
  broker:
    pattern: fan_out
    outputs:
      - inproc: backend1
      - inproc: backend2
