input:
  label: "ping_generator"
  generate:
    mapping: |
      root.ts = now()
      root.unix = timestamp_unix()
    interval: 1s
    count: 0
    batch_size: 7
    auto_replay_nacks: true

pipeline:
  processors:
    - mapping: |
        root = this

output:
  label: "udp_send"
  socket:
    network: "udp"
    address: "127.0.0.1:${UDP_PORT}"
    codec: lines
