input:
  file:
    paths: 
     - /Users/dave/dev/redpanda/brokers-3/data/win-*  # No default (required)
    scanner:
      lines: {}
    delete_on_finish: true
    auto_replay_nacks: true

buffer:
  none: {}

pipeline:
  threads: -1
  processors:
    - mapping: "root = this"  

output:
  kafka_franz:
    seed_brokers: 
      - localhost:19092
    topic: "win-some" # No default (required)
    key: "" # No default (optional)
    partitioner: "least_backup" 
    client_id: win-some
    rack_id: "localhost"
    idempotent_write: true
    metadata:
      include_prefixes: []
      include_patterns: []
    max_in_flight: 10
    timeout: 10s
    batching:
      count: 5000
      byte_size: 1048000 # 1 mb - 500 bytes 
      period: "2s"
      check: ""
      processors: [] # No default (optional)
    max_message_bytes: 1MB
    compression: "snappy" # No default (optional)
    tls:
      enabled: false
      skip_cert_verify: false
      enable_renegotiation: false
      root_cas: ""
      root_cas_file: ""
      client_certs: []
    sasl: [] # No default (optional)
    timestamp: ${! timestamp_unix() } 