# 
input:
  file: 
    paths: [ ./input ]
    scanner:
       re_match:
          pattern: <\d+> 
          max_buffer_size: 65536

pipeline:
  processors:
    - mapping: |
        root = content()

output:
  stdout: {}