input:
  label: "generators"
  broker:
    inputs:
      - generate:
          mapping: root = "hello world " + now() # No default (required)
          interval: 1s
          count: 0
          batch_size: 1
          auto_replay_nacks: true
      - generate:
          mapping: root = "[WIN] hello world " + now() # No default (required)
          interval: 3s
          count: 0
          batch_size: 1
          auto_replay_nacks: true